TASK-1A

In [1]:
import pandas as pd
import numpy as np

In [2]:
#read the dataset
df = pd.read_csv("student_dataset_100_rows.csv")

In [3]:
#display the dataset
df.head()

  StudentID   Name   Age  Gender  Math_Score  English_Score  Science_Score
0      S001  Meena  22.0  Female         NaN           96.0           95.0
1      S002  Priya   NaN    Male        36.0           72.0           75.0
2      S003  Varun  17.0    Male        82.0            NaN           51.0
3      S004  Sneha  22.0    Male        71.0            NaN          100.0
4      S005  Divya  17.0  Female        75.0           80.0            NaN

In [4]:
df.tail()

,StudentID,Name,Age,Gender,Math_Score,English_Score,Science_Score
95,S096,Manoj,19.0,Male,44.0,35.0,91.0
96,S097,P resemble,18.0,Female,82.0,61.0,65.0
97,S098,Arjun,21.0,Male,86.0,52.0,94.0
98,S099,Priya,19.0,Female,87.0,69.0,51.0
99,S100,Neha,22.0,Female,47.0,89.0,65.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StudentID      100 non-null    str
 1   Name           100 non-null    str
 2   Age            99 non-null     float64
 3   Gender         100 non-null    str
 4   Math_Score     99 non-null     float64
 5   English_Score  98 non-null     float64
 6   Science_Score  99 non-null     float64
dtypes: float64(4), str(3)
memory usage: 5.6 KB

In [6]:
#show the number of columens and rows
df.dtypes

StudentID            str
Name                 str
Age              float64
Gender               str
Math_Score       float64
English_Score    float64
Science_Score    float64
dtype: object

In [7]:
df.count()

StudentID        100
Name             100
Age               99
Gender           100
Math_Score        99
English_Score     98
Science_Score     99
dtype: int64

In [8]:
df.sort_values(by="Age", ascending=True)

   StudentID    Name   Age  Gender  Math_Score  English_Score  Science_Score
2       S003   Varun  17.0    Male        82.0            NaN           51.0
4       S005   Divya  17.0  Female        75.0           80.0            NaN
11      S012   Meena  17.0    Male        81.0           88.0           65.0
10      S011  Vikram  17.0    Male        50.0           61.0           79.0
12      S013   Rahul  17.0    Male        42.0           99.0           42.0
..       ...     ...   ...     ...         ...            ...            ...
71      S072   Manoj  22.0    Male        36.0           72.0           98.0
90      S091   Varun  22.0  Female        41.0           54.0          100.0
92      S093   Sneha  22.0  Female        89.0           52.0           62.0
99      S100    Neha  22.0  Female        47.0           89.0           65.0
1       S002   Priya   NaN    Male        36.0           72.0           75.0

[100 rows x 7 columns]

In [9]:
df.sort_values(by="Age", ascending=False)

   StudentID    Name   Age  Gender  Math_Score  English_Score  Science_Score
0       S001   Meena  22.0  Female         NaN           96.0           95.0
3       S004   Sneha  22.0    Male        71.0            NaN          100.0
7       S008  Vikram  22.0    Male        88.0           47.0           52.0
31      S032   Varun  22.0    Male        56.0           52.0           88.0
9       S010   Pooja  22.0  Female        64.0           65.0           56.0
..       ...     ...   ...     ...         ...            ...            ...
76      S077   Aarav  17.0  Female        58.0           52.0           44.0
69      S070   Rahul  17.0    Male        88.0           80.0           72.0
78      S079   Varun  17.0  Female        40.0           76.0           83.0
89      S090  Nikhil  17.0  Female        64.0           69.0           81.0
1       S002   Priya   NaN    Male        36.0           72.0           75.0

[100 rows x 7 columns]

In [10]:
df.nunique().sum()

np.int64(281)

In [11]:
df.describe()

             Age  Math_Score  English_Score  Science_Score
count  99.000000   99.000000      98.000000      99.000000
mean   19.494949   70.666667      65.612245      67.030303
std     1.774960   20.287223      19.072641      19.509524
min    17.000000   35.000000      35.000000      35.000000
25%    18.000000   51.000000      51.250000      51.000000
50%    20.000000   74.000000      67.500000      66.000000
75%    21.000000   89.000000      80.750000      83.000000
max    22.000000  100.000000     100.000000     100.000000

In [12]:
df.shape

(100, 7)

TASK-1B

In [13]:
df2 = pd.read_csv("airline_booking_records.csv")
df2.head()

,Booking_ID,Source,Destination,Flight_ID,Class,Amount,Booking_Date,Travelled_Date
0,B1000,Bangalore,Kolkata,AI200,Economy,10732,2025-01-01,2025-01-07
1,B1001,Delhi,Kolkata,AI201,Economy,29243,2025-01-02,2025-01-08
2,B1002,Chennai,Mumbai,AI202,Economy,38403,2025-01-03,2025-02-16
3,B1003,Bangalore,Kolkata,AI203,First,40103,2025-01-04,2025-02-19
4,B1004,Bangalore,Delhi,AI204,First,49993,2025-01-05,2025-02-14

In [14]:
df2.isnull().sum()

Booking_ID        0
Source            0
Destination       0
Flight_ID         0
Class             0
Amount            0
Booking_Date      0
Travelled_Date    0
dtype: int64

In [15]:
df2_cleaned = df2.dropna(axis=1, how='all')
df2_cleaned

,Booking_ID,Source,Destination,Flight_ID,Class,Amount,Booking_Date,Travelled_Date
0,B1000,Bangalore,Kolkata,AI200,Economy,10732,2025-01-01,2025-01-07
1,B1001,Delhi,Kolkata,AI201,Economy,29243,2025-01-02,2025-01-08
2,B1002,Chennai,Mumbai,AI202,Economy,38403,2025-01-03,2025-02-16
3,B1003,Bangalore,Kolkata,AI203,First,40103,2025-01-04,2025-02-19
4,B1004,Bangalore,Delhi,AI204,First,49993,2025-01-05,2025-02-14
5,B1005,Delhi,Delhi,AI205,Business,28757,2025-01-06,2025-02-18
6,B1006,Mumbai,Kolkata,AI206,Business,22935,2025-01-07,2025-01-23
7,B1007,Delhi,Goa,AI207,Economy,23430,2025-01-08,2025-02-28
8,B1008,Bangalore,Mumbai,AI208,Economy,47512,2025-01-09,2025-02-01
9,B1009,Bangalore,Goa,AI209,First,22650,2025-01-10,2025-02-11
10,B1010,Chennai,Kolkata,AI200,Business,25089,2025-01-11,2025-01-16
11,B1011,Bangalore,Goa,AI201,Business,40230,2025-01-12,2025-01-31
12,B1012,Chennai,Mumbai,AI202,First,26983,2025-01-13,2025-02-22
13,B1013,Bangalore,Mumbai,AI203,Economy,32152,2025-01-14,2025-03-13
14,B1014,Mumbai,Goa,AI204,Business,43665,2025-01-15,2025-02-01
15,B1015,Bangalore,Pune,AI205,Business,24921,2025-01-16,2025-03-04
16,B1016,Chennai,Mumbai,AI206,Business,35469,2025-01-17,2025-02-11
17,B1017,Chennai,Kolkata,AI207,Business,46984,2025-01-18,2025-02-03
18,B1018,Chennai,Kolkata,AI208,Business,14921,2025-01-19,2025-01-28
19,B1019,Bangalore,Kolkata,AI209,First,46804,2025-01-20,2025-01-31
20,B1020,Chennai,Pune,AI200,First,10163,2025-01-21,2025-01-30
21,B1021,Hyderabad,Kolkata,AI201,First,13072,2025-01-22,2025-03-15
22,B1022,Mumbai,Goa,AI202,Economy,45619,2025-01-23,2025-03-21
23,B1023,Bangalore,Pune,AI203,Business,15877,2025-01-24,2025-02-01
24,B1024,Chennai,Mumbai,AI204,First,26430,2025-01-25,2025-02-11
25,B1025,Mumbai,Pune,AI205,Business,9871,2025-01-26,2025-03-08
26,B1026,Bangalore,Kolkata,AI206,Business,15599,2025-01-27,2025-03-25
27,B1027,Mumbai,Kolkata,AI207,Business,10496,2025-01-28,2025-03-14
28,B1028,Hyderabad,Goa,AI208,Business,32675,2025-01-29,2025-02-17
29,B1029,Bangalore,Mumbai,AI209,Economy,39921,2025-01-30,2025-02-19
30,B1030,Chennai,Mumbai,AI200,First,41523,2025-01-31,2025-02-25
31,B1031,Delhi,Pune,AI201,First,8797,2025-02-01,2025-03-13
32,B1032,Chennai,Kolkata,AI202,Economy,11219,2025-02-02,2025-03-02
33,B1033,Bangalore,Kolkata,AI203,Business,23246,2025-02-03,2025-02-23
34,B1034,Chennai,Pune,AI204,Business,32999,2025-02-04,2025-02-22
35,B1035,Delhi,Delhi,AI205,Economy,24321,2025-02-05,2025-04-04
36,B1036,Delhi,Kolkata,AI206,Economy,27129,2025-02-06,2025-03-04
37,B1037,Delhi,Mumbai,AI207,Economy,49504,2025-02-07,2025-04-01
38,B1038,Chennai,Pune,AI208,First,26676,2025-02-08,2025-04-03
39,B1039,Bangalore,Pune,AI209,Business,39230,2025-02-09,2025-02-19
40,B1040,Chennai,Goa,AI200,First,19723,2025-02-10,2025-03-28
41,B1041,Delhi,Kolkata,AI201,Business,25591,2025-02-11,2025-03-23
42,B1042,Hyderabad,Kolkata,AI202,First,34752,2025-02-12,2025-02-17
43,B1043,Delhi,Mumbai,AI203,Economy,31605,2025-02-13,2025-03-21
44,B1044,Delhi,Delhi,AI204,First,14021,2025-02-14,2025-02-24
45,B1045,Bangalore,Mumbai,AI205,Economy,28006,2025-02-15,2025-03-22
46,B1046,Chennai,Delhi,AI206,Business,11560,2025-02-16,2025-02-21
47,B1047,Bangalore,Goa,AI207,Business,33332,2025-02-17,2025-04-12
48,B1048,Chennai,Mumbai,AI208,Business,39055,2025-02-18,2025-04-14
49,B1049,Delhi,Mumbai,AI209,Economy,29368,2025-02-19,2025-04-01

In [16]:
df2_cleaned.duplicated().sum()

np.int64(0)

In [17]:
df2_cleaned[df2_cleaned.duplicated()]

Empty DataFrame
Columns: [Booking_ID, Source, Destination, Flight_ID, Class, Amount, Booking_Date, Travelled_Date]
Index: []

In [18]:
df2_no_duplicates = df2_cleaned.drop_duplicates()

In [19]:
df2_no_duplicates.duplicated().sum()

np.int64(0)